### ISSUE TITLE
How to set the artboard color？

### ISSUE THREAD

**Issue by dalaoque** [xiaokaike/vue-color#100]
Hello hero, I have a string of similar 'rgba (XXX, XXX, XXX, 1)', is taken from the css, how do I make the color drawing to dynamically display these colors?

setOption ()?
v-model?

Very grateful!

**Comment by linx4200** [comment]
I am sorry,  I am confused about what you want to do. Could you provide your use case ?

**Comment by dalaoque** [comment]
Haha, I just solved the problem

like this

const rgba = 'rgba(208,2,27,1)'

<sketch-picker v-model="rgba"></sketch-picker>

**Comment by dalaoque** [comment]
Haha, I just solved the problem

Like this

```
const rgba = 'rgba(208,2,27,1)'

<sketch-picker v-model="rgba"></sketch-picker>
```

Thanks!

**Comment by xiaokaike** [comment]
@dalaoque you can use `tinycolor2` to transform color

```
import tinycolor from 'tinycolor2'

const defaultColor = {
  "hsl": tinycolor('rgba(208,2,27,1)').toHsl()
}

<sketch-picker v-model="defaultColor"></sketch-picker>
```
