### ISSUE TITLE
Document issue: wrong object structure for rgba format color

### ISSUE THREAD

**Issue by hjlld** [xiaokaike/vue-color#102]
if you use rgba as the default color format, and pass it with v-model, you should use:

```
<vue-color v-model="color">
...
data(){
    return {
        color: {
            r: 1,
            g: 1,
            b: 1,
            a: 1,
        }
    }
}
...
```

What the document told you is wrong:

```
color:{
  rgba: {
    r: 25,
    g: 77,
    b: 51,
    a: 1
  },
}
```

Because tinycolor.toRgb() dosen't support this documented object format.

**Comment by hjlld** [comment]
any news about this issue?

**Comment by linx4200** [comment]
We will fix the document in the next release, estimated in next week.
Thanks for your feedback.

**Comment by linx4200** [comment]
Have updated document. Thanks!
