### ISSUE TITLE
Strange language suggestion when including the colorpicker

### ISSUE THREAD

**Issue by franktopel** [xiaokaike/vue-color#104]
When I include the color-picker in my app, the resulting page asks  "This page is in `<Danish>`. Do you want to translate it?" even though I put a `html lang="en"` in my code.

See http://connexo.de/vue-plotly using latest Chrome stable.

Any idea why this is happening?

**Comment by linx4200** [comment]
I don't get any translation popup chrome which version is 64.0.3282.119

**Comment by linx4200** [comment]
Closing this issue for now. Let us know if you have anything to add.
