### ISSUE TITLE
cant change hex value

### ISSUE THREAD

**Issue by kisin** [xiaokaike/vue-color#108]
changing the hex text inside the color picker doesnt have any visible effect on color picker

**Comment by linx4200** [comment]
Could you give an example?

**Comment by linx4200** [comment]
In my tests, when I change the hex inside the components that contain hex input, all components can be rerendered.

If you encounter this problem again, please provide a reproducible demo, and reopen this issue. Thanks.

**Comment by douglasncon** [comment]
Hi there, I'm actually working on that as well.
I've set hex property but I couldn't get any effects, as follow:

```
<template>
<div>
    <div class="form-group">
        <label>Colour</label><br/>
        <sketch-picker v-model="colours" />
    </div>

    <button class="btn btn-sm btn-outline-primary" @click="test" >test</button>
</div>
</template>
```
```
<script>
import { Sketch } from "vue-color";
export default {
  components: {
    "sketch-picker": Sketch
  },
  data() {
    return {
      label: {},
      colours: {
        hex: undefined,
        hsl: {},
        hsv: {},
        rgba: {},
        a: undefined
      }
    };
  },  
  methods: {   
    test(){
        this.colours.hex = '#C26363';
    }
  }
};
</script>
```

In addition, I might say that this component was open in a slot of parent component, but, as the sample, I've set hex with a test colour.
