### ISSUE TITLE
RGB fields show wrong values on small numbers

### ISSUE THREAD

**Issue by IceOnFire** [xiaokaike/vue-color#109]
Hi,

First of all thank you and congratulations for this amazing component!

I saw that if you input values such as '1', '2', '3' in the RGB fields, the moment you write the '3' all values show up as '2'. Same for '3', 2', '1', which yields all '1's, or other combinations. The underlying value is correct, it's just a presentation issue.

Antony

**Comment by mrcointreau** [comment]
+1

**Comment by linx4200** [comment]
Fixed in `2.4.4`. Thanks!

**Comment by mrcointreau** [comment]
@linx4200 Thank you very mich for fixing this!
