### ISSUE TITLE
cant preventDefault and stop Propegation

### ISSUE THREAD

**Issue by challen03** [xiaokaike/vue-color#110]
I registered the cancellation event for the outermost layer, but this component failed to stop the bubble.

**Comment by linx4200** [comment]
Could you provide more info about your problem, like a demo.  Help us to figure out what's your purpose.

**Comment by challen03** [comment]
I need to cancel the outside of the component to cancel the component to display, and click the event on the most external registration, but I can't cancel the bubble in the input event, causing the component to be unable to display.

**Comment by linx4200** [comment]
I assume you can speak Chinese. Can we speak in Chinese? 😂

**Comment by challen03** [comment]
这么尴尬的吗，这是有道翻译过来的，不好意思了，我也没细看他翻译成什么了...
vue-color组件有没有提供阻止冒泡和默认事件的方法，因为在你暴露的input方法上不能用.stop.prevent，
但是我需要在除该组件外的地方点击取消该组件的展示（现在用css tabIndex解决了）,由于当时没有找到暴露的阻止方法，所以解决起来比较费力

**Comment by linx4200** [comment]
可以参考这个 issue: https://github.com/xiaokaike/vue-color/issues/90

**Comment by challen03** [comment]
好的，感谢

**Comment by humblecoder** [comment]
So, what was the actual solution (in English 🤣 )?

**Comment by humblecoder** [comment]
@xiaokaike apologies for being obtuse, but is there an example of using an additional plugin in this manner with an existing component?  Do I need to wrap it with SFC?  🤔

**Comment by humblecoder** [comment]
Never mind.  Used a `directive`.  Thanks.
