### ISSUE TITLE
Cannot read property 'clientWidth' of undefined

### ISSUE THREAD

**Issue by evolutionjay** [xiaokaike/vue-color#119]
<img width="588" alt="2018-03-02 6 22 40" src="https://user-images.githubusercontent.com/4468540/36894642-08bb2694-1e47-11e8-8c8f-2531b63dcd2b.png">
Here in nested into a dynamic vNode, probably because of unable to get the container and cause an error

using  `sketch`  component

**Comment by linx4200** [comment]
Please provide demo that can reproduce this issue.

**Comment by evolutionjay** [comment]
@linx4200  Sorry , The reason I found the problem is that a component's v-model conflicts with skecth's @change for unknown reasons. It's not your business, please close this issues

**Comment by lk77** [comment]
Hello,

i have the same issue :+1: 

```
Uncaught TypeError: Cannot read property 'clientWidth' of undefined
    at VueComponent.handleChange (vue-color.min.js?c345:formatted:992)
```
