### ISSUE TITLE
update colors.hex after register component not work

### ISSUE THREAD

**Issue by tfzxyinhao** [xiaokaike/vue-color#12]
```
var sectionModel = {
    id:'',
    icon:'',
    title :'',
    link:'',
    colors : {
        hex: '#ff00ff'
    }
};

Vue.component('color-picker', VueColor.Chrome);

sectionModel.colors.hex = `#ff0000`;
```

update colors.hex not trigger the ui's color changed of events
ui's color still is '#ff00ff'

**Comment by xiaokaike** [comment]
did you set the colors in template? just like this
```
<color-picker :colors.sync="sectionModel.colors"></color-picker>
```

**Comment by tfzxyinhao** [comment]
```
<color-picker :colors.sync="colors"></color-picker>
```

i set it in template

**Comment by cassioscabral** [comment]
Returning the sectionModel in data might be the problem, I believe Vue needs to know the data beforehand to be reactive, if you want to do dynamically you should use vm.set for each sectionModel properties inside a life cycle hook.

**Comment by tfzxyinhao** [comment]
I don't find any problem of my data, and the data change by correct way
