### ISSUE TITLE
Unknown custom element: <photoshop-picker> - did you register the component correctly? For recursive components, make sure to provide the "name" option

### ISSUE THREAD

**Issue by zhangjuncdtc** [xiaokaike/vue-color#121]
"vue-color": "^2.4.5",
"element-ui": "^2.1.0"

import { photoshop } from 'vue-color'
  import {utils} from '@/assets/js/utils'
  export default {
    name: 'YxAddOrg',
    components: {
      YxCollapse,
      YxTenantPicUpload,
      'photoshop-picker': photoshop
    },

**Comment by xiaokaike** [comment]
photoshop change to Photoshop ?
```
import { Photoshop } from 'vue-color'
```
