### ISSUE TITLE
Multiple colors selection

### ISSUE THREAD

**Issue by QDSNALEXWU** [xiaokaike/vue-color#122]
For some components, it would be nice if we can pick multiple colors.

**Comment by QDSNALEXWU** [comment]
For example, for sketch or compact components, it would be a good feature if user can pick more than one color and the color prop use an array to keep track of whatever choices the user has clicked on. 
<img width="258" alt="screen shot 2018-03-16 at 2 38 24 pm" src="https://user-images.githubusercontent.com/16129049/37507051-ba979844-2927-11e8-9821-e69de0e6bace.png">

**Comment by linx4200** [comment]
We're sorry that we are not gonna implement this feature. It is not very common to use multiple select. 
For now, maybe you need to create your own component to do that.

If anyone else bring this up, we will consider this feature again.

Thank you.
