### ISSUE TITLE
Add .babelrc to .npmignore

### ISSUE THREAD

**Issue by kedrzu** [xiaokaike/vue-color#124]
Your `.babelrc` file is published to npm. This causes i.e that if I want to transpile my project along with dependencies, I am dependent on your babel configuration (plugins, presets, etc).

Could you please add `.babelrc` file to `.npmignore`?

**Comment by linx4200** [comment]
> Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

According to [Babel's documentation](https://babeljs.io/docs/usage/babelrc/),   a `.babelrv` file in `./node_modules/vue-color` would not affect your project.

**Comment by kedrzu** [comment]
Let's say you have a project with some third-party dependencies written in ES6. To be ES5 compliant you would use babel to transpile your project as well as your dependencies. When you include i.e. `babel-loader` for `node_modules` dependencies it would do the job.

And, as you pointed out, `babel` will traverse directory tree to search for `.babelrc` file. Because `vue-color` includes its own `.babelrc` in npm package, the result is that it is being used by `babel`, along with your configured presets and plugins. 

This results in indirect dependencies of my project to your `babel` setup and the need to install all the presets and plugins you use.

As a reference look at the core `vue` project. They do use `babel` but don't include `.babelrc` in their final npm package. Adding this file to `.npmignore` would result in `.babelrc` file not being published to npm.

**Comment by linx4200** [comment]
Sorry for the delay. Thanks for explanation.  It's released on `2.4.6`
