### ISSUE TITLE
sketch v-model : color.rgba has changed, but the color don't change

### ISSUE THREAD

**Issue by dylan921208** [xiaokaike/vue-color#126]
like this :
color: { hex:  '10A0E9',  rgba:  { r: 16, g: 160, b: 233, a: 1 },  source: 'rgba' }
then i change the color.rgba: { r: 246, g: 84, b: 84, a: a } but the color has no change

**Comment by linx4200** [comment]
Hi, could you give us a complete example of your usage, so we can know what's happening directly. Thanks.

**Comment by dylan921208** [comment]
in my tempalte
`<sketch-picker `v-model="color"></sketch-picker>`
`data(){
 color: { hex: '10A0E9', rgba: { r: 16, g: 160, b: 233, a: 1 }, source: 'rgba'},
},
mounted() {
setTimeout(() => {
      this.color.rgba = { r: 246, g: 84, b: 84, a: 1 }
    }, 100)
}`
the page show color just like this picture
￼
![1522204515745](https://user-images.githubusercontent.com/28706090/38005552-b97d519c-3273-11e8-80bb-65fbfce22092.jpg)
in vue-devtools 
![1522204603465](https://user-images.githubusercontent.com/28706090/38005599-ee9e18fc-3273-11e8-9cfc-7a54df05e002.jpg)
but when i use like this , it works
`<sketch-picker `v-model="color" v-if="color.hex"></sketch-picker>`
`data() { color: { hex: null }}，mounted() {setTimeout(() => {
      this.color.hex = '#000000'
    }, 100)}
`

**Comment by linx4200** [comment]
you can do this:

``` 
data () {
   color: { r: 16, g: 160, b: 233, a: 1 }
}
`

**Comment by dylan921208** [comment]
thanks
