### ISSUE TITLE
Component is not accessible

### ISSUE THREAD

**Issue by aral** [xiaokaike/vue-color#127]
Currently, people who rely on assistive technologies cannot use any site/app that uses this component. This means, for example, that this component cannot be used for government sites where laws prohibit discrimination based on physical abilities and that it cannot be used on sites/app that care about being accessible to people with disabilities.

## To reproduce

1. Activate a screen reader (e.g., VoiceOver on Mac)
2. On a page that has the vue-color component on it, attempt to select and use the vue-color component using the screen reader controls

## What should happen

You should be able to see, select and use the vue-color component via the screenreader.

## What actually happens

The vue-color component is entirely invisible to the accessibility subsystems. You cannot see, select, or use it using assistive technologies like a screen reader.

**Comment by linx4200** [comment]
Thanks for your remind. We're not taking accessibility very seriously before.  Will pay more attention in next the big release 3.0 which we are working on it.

If any news, I will update this issue. Thanks.

**Comment by mtheoryx** [comment]
Are there already-identified items slated for the 3.0 release? I couldn't find a lot of details in the project milestones. Cheers!

**Comment by linx4200** [comment]
we already released [v2.5.0](https://github.com/xiaokaike/vue-color/releases/tag/2.5.0) to improve accessibility (#129).  If it's not enough, please let us know and reopen this issue. Thanks!
