### ISSUE TITLE
luminosity value of 1 in Slider swatches array breaks activeOffset() function

### ISSUE THREAD

**Issue by phivk** [xiaokaike/vue-color#134]
As I suggested in https://github.com/xiaokaike/vue-color/issues/118 I am interested in adding luminosity values of 1 (white) and 0 (black) to the swatches array in `Slider.vue`, like this:

```
swatches: ['1', '.83', '.67', '.50', '.33', '.17','0']
```

All displays fine, but using `1` as a value in the swatches array, breaks the functionality of the `activeOffset()` function that determines to which swatch the `active` class will be added:

```
activeOffset () {
  if (Math.round(this.colors.hsl.s * 100) / 100 === 0.50) {
    return Math.round(this.colors.hsl.l * 100) / 100
  }
  return 0
}
```

Problem seems to be that in case I select the swatch with luminosity 1, the value of `this.colors.hsl.s` becomes 0 and therefore `activeOffset()` returns 0 (thus setting the active class to the wrong swatch).

Not sure why that if statement is there in `activeOffset()`, but removing it fixes this issue.

**Comment by linx4200** [comment]
fix in v2.6.0, which will be released soon.
