### ISSUE TITLE
Customizing compact picker

### ISSUE THREAD

**Issue by tharangachaminda** [xiaokaike/vue-color#138]
How can we keep just a few colors and remove the rest. If we can do customization like that, would be awesome. Great work!

**Comment by phil-w** [comment]
Ditto, need to be able to set swatches up for this one to be workable.

**Comment by andrewmcconville** [comment]
we did this:
`<compact-picker :palette="palette" :value="colors" @input="updateValue" />`
and then:
`private palette = ['#B0BC00', '#68BC00', '#16A5A5', '#009CE0', '#7B64FF', '#FA28FF'];`
