### ISSUE TITLE
Could you make a no vuejs version.

### ISSUE THREAD

**Issue by suhebater** [xiaokaike/vue-color#139]
I need a  jQuery  version.

**Comment by xiaokaike** [comment]
so funny

**Comment by linx4200** [comment]
https://www.google.com/search?q=jquery+color+picker

Please use Google.

**Comment by suhebater** [comment]
I like this picker design. But do not want to use Vuejs.

**Comment by linx4200** [comment]
Sorry, this is `vue-color`.  Vue is the core.

**Comment by suhebater** [comment]
Thanks for your reply.
