### ISSUE TITLE
passing a Hex as a prop doesnt change color

### ISSUE THREAD

**Issue by ChadTaljaardt** [xiaokaike/vue-color#152]
Hello, 

When i pass a Hex value to the colour picker, the picker doesn't update to show the colour that was passed in. I have used Vue dev tools to ensure that prop gets passed and it does, but the UI doesn't update to show the colour that was passed.

**Comment by linx4200** [comment]
Please do provide a reproduction repo for this issue.

**Comment by linx4200** [comment]
Closing this issue for now. Let us know if you have anything to add.

**Comment by egeersoz** [comment]
I am having the same issue, so it should be pretty easy to reproduce.

```
<chrome-picker :disableAlpha="true" v-model="organization.primaryColor" />
```

```
created() {
  this.organization.primaryColor.hex = org.brand_primary_color
}
```

So far so good. However, inside a function if I do:

```
this.organization.primaryColor.hex = 'some hex value'
```

The color picker doesn't update.
