### ISSUE TITLE
add 'ok' button

### ISSUE THREAD

**Issue by rassemdev** [xiaokaike/vue-color#155]
I'm using your picker in my project. In there i need an extra button where user pick the button and click ok and then it will be add to the input field. Is there any way to add 'ok' button in chrome picker? I don't want any button outside of that picker component

**Comment by linx4200** [comment]
We try to stay alike to the color picker in Chrome and there is no room for an ok button in chrome picker. 
In version 3.0, we will show you a way to create your own picker using `vue-color` components.
