### ISSUE TITLE
一般进入的是一个字符串，但是返回的是一个数组，是通过v-model绑定的，怎样进行过滤啊

### ISSUE THREAD

**Issue by CrazyApple1** [xiaokaike/vue-color#158]
比如进入的是： #FFFFFF，

返回的变成了一个对象，不合理啊，数据都乱了啊

{ "hsl": { "h": 0, "s": 0.7699115044247787, "l": 0.2712, "a": 0 }, "hex": "#7A1010", "hex8": "#7A101000", "rgba": { "r": 122, "g": 16, "b": 16, "a": 0 }, "hsv": { "h": 0, "s": 0.87, "v": 0.48, "a": 0 }, "oldHue": 0, "source": "hsva", "a": 0 }
、、、、、、、、、、、、、、、、、
求解决方法
求解决方法
求解决方法 help help help

**Comment by CrazyApple1** [comment]
``

**Comment by linx4200** [comment]
用的是哪个组件呢？
可以用组件 emit 的 change 事件，获得对象里的 `hex` 或 `hex8`

**Comment by CrazyApple1** [comment]
我使用的是Sketch这个组件，发现只能通过v-model绑定，返回数据不知道如何进行过滤数据才合适

**Comment by linx4200** [comment]
`<sketch-picker :color="color" @change="onChange" />`

`onChange` 里可以过滤

**Comment by CrazyApple1** [comment]
大佬，可不可以设计成加个配置参数，决定返回的值是什么类型的啊，这样感觉比较麻烦，一下子发现不了啊，我被这个问题搞的欲生欲死啊，多写了上百行代码，最后用compute的set方法过滤了。。。。。。或者文档说明一下啊

**Comment by linx4200** [comment]
谢谢您的提议，在 `3.0` 版本中会废除 `v-model` 形式传入参数，并且会完善文档。的确有必要可以指定返回值的类型，`3.0` 版本中一并加入此功能。

那么先关闭 issue 了，谢谢。
