### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by EmilMoe** [xiaokaike/vue-color#16]
I'm trying to import this library to my project, but gulp with browserify keeps complaining.

I have added this to my main.js file

``` javascript
Vue.use(require('vue-color/dist/vue-color.js'));
```

**Comment by applefreak** [comment]
Couldn't figure it out either... 😢

**Comment by karlerss** [comment]
Had the same problem with laravel vue setup.

An ugly workaround was npm stylus and stylus-loader.

Then require it from source:

Vue.component('slider-picker', require('../../../node_modules/vue-color/src/index.js').Slider);

**Comment by jcorcuera** [comment]
This way worked for me:

```
```

**Comment by cassioscabral** [comment]
I guess this is just how the example is written, if @jcorcuera  solution worked it shouldn't be a problem for someone to open a PR to update the Readme. If anyone want to take this, feel free to do it. I will check your PR gladly. But try to import just one Component if that is possible with require, should be a better example(requiring just the Photoshop for example)
