### ISSUE TITLE
Recommendations for accessibility improvements

### ISSUE THREAD

**Issue by NateWr** [xiaokaike/vue-color#160]
I saw that you added `aria-label` and `role` attributes to some of the buttons. In addition, it would be nice if the relationship of the input fields to other helpful text could be defined by passing `aria-labelledby` and `aria-describedby` props to the component, which would then be attached to the input fields.

Also, a non-technical accessibility requirement for us would be the ability to translate the existing labels in the component. Would you consider a `strings` prop for overriding any English-language labels you've applied to buttons in the component?

**Comment by linx4200** [comment]
I see your point. 

- Add improve accessibility by adding `aria-labelledby` and `aria-describedby`.
- Allow to customize labels in favor of i18n.

I think I can manage these improvements within this week and release a new version. Thanks.

**Comment by NateWr** [comment]
Thanks, we've updated! :+1:
