### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by BeardScript** [xiaokaike/vue-color#162]
Hi, I'm Paul. First of all, I'd like to thank the creators of this plugin. It's really nice. But I'd like to point out that the lack of documentation makes it hard to understand the product's capabilities. I needed to expand the preset colors of the Sketch component and I had to go to the source code to check if there was a property I could use, and there was one indeed (:predefinedColors). This could be a drag for newcomers whom would wrongly assume that vue-color won't let them load their own predefined colors.

I offer myself to help adding this to the docs.

**Comment by linx4200** [comment]
Documentation need to be improved, for sure.
Feel free to submit pull requests.

**Comment by LeonSkrilec** [comment]
I think it is actually :presetColors and it accepts array of HEX values. Maybe helps anyone...

**Comment by BeardScript** [comment]
> I think it is actually :presetColors and it accepts array of HEX values. Maybe helps anyone...

Yes indeed, that's the right property and it does take an array, although, you can fill it with either HEX values and as far as I know also an rgb/rgba like this: 'rgba(0,0,0,0)'. I'll send a PR to update the docs as soon as I have time. This is a good thread to throw in any other details that might be missing from the docs.

**Comment by LeonSkrilec** [comment]
That would be great @BeardScript . I also found myself digging the source code to find appropriate settings. Thanks for your effort.

**Comment by RaymondAtivie** [comment]
Has this been documented? Any link to a documentation?

**Comment by BeardScript** [comment]
I'm sorry I got caught up on work and completely forgot about this. I'll fork and send PR ASAP.
