### ISSUE TITLE
Swap H/S/L positions on picker

### ISSUE THREAD

**Issue by k-yle** [xiaokaike/vue-color#166]
Hi, sorry if this has been requested before. Is it possible to swap the axis around so that the hue is part of the main grid and the saturation is on the separate slider?

This is how colour pickers are setup in the stage-lighting industry, because saturation is used for the dimmer/intensity. 

See the image below. 
<img width="387" alt="colour picker" src="https://user-images.githubusercontent.com/16009897/48754501-b524d500-ecf6-11e8-90fc-c4ba1ea91642.PNG">

Thanks for the great component!

**Comment by linx4200** [comment]
Sorry for the late reply. You can achieve by  building your own custom picker which will be provided in 3.0 release. Related: #186 .
