### ISSUE TITLE
Unable to use own sliders to edit Chrome picker

### ISSUE THREAD

**Issue by alanzeng17** [xiaokaike/vue-color#169]
Not sure if I'm just straight up doing something wrong(new to vue), but I'm trying to build my own RGB sliders to make it easier to adjust the RGB values of the picker. I've currently connected the sliders using `:value=colors.rgba.r @input="updateValue`. So far, I can use the Chrome picker to change the slider values but not the opposite. I'm able to update my own var color variable using my slider, but it doesn't seem to change the picker RGB values, even though the Chrome Picker is connected using v-model:"colors".

**Comment by linx4200** [comment]
Seems like it's a usage problem. Please reopen if you still have problem about it. Thanks!
