### ISSUE TITLE
Customize presetColors

### ISSUE THREAD

**Issue by oknoorap** [xiaokaike/vue-color#17]
I think it will be awesome if we can customize presetColors.

**Comment by randarp** [comment]
So it ends up this is an undocumented feature.  In my case, I have a component that wraps the color picker, but I've assigned it a ref.

<sketch-picker ref="sketch" v-show="pickerOpen" v-model="colorValue" @change-color="onChange"></sketch-picker>

When my component is mounted, you can change the default by manipulating the presetColors array at that time.

mounted: function() {
this.$refs.sketch.presetColors = ['#323c44','#cd263a','#8d8d8d','#9e00ff','#0000ff','#00da00','#dada00','#ff8d00','#ff00de','#a65628','#848484'];
},

It seems to be smart with the number of items in the array.  You probably just want to make it a multiple of 8 or it won't be square.

But yes, it would be nice if there was a simpler option to do this.

**Comment by rohmanhm** [comment]
> I think it will be awesome if we can customize presetColors.

Yeah, that was great!! 😃
It would be nice if we have add and remove button to color presets.

**Example:**
![image](https://cloud.githubusercontent.com/assets/7524911/23882870/1145cb88-0896-11e7-9319-2c909c0907f8.png)

**Comment by linx4200** [comment]
The swaches can be customize now! Please upgrade to the latest version. And the usage is down blow:

```html
/* presetColors accepts an array of colors */
<sketch v-model="colors" :presetColors="presetColors"></sketch>
```

And the document will catch up sooooooon!

Thanks for your patience!
