### ISSUE TITLE
[Bug] Sketch 拖动颜色滑块无效

### ISSUE THREAD

**Issue by StringKe** [xiaokaike/vue-color#196]
![image](https://user-images.githubusercontent.com/31089228/72237958-42239f80-3617-11ea-9f2a-ce202657d2ed.png)
默认通过css隐藏了不需要的内容
```
<sketch v-model="defaultColor" @input="changeFillColor"/>
```
```
defaultColor = '#000';
```
在首次拖动时候 `Sketch` 组件内的 `hsl` `hsv` `oldHue` 值均会变动，但 `RGB` 值不会

![image](https://user-images.githubusercontent.com/31089228/72238084-b52d1600-3617-11ea-9b97-6717c53cbed4.png)
![image](https://user-images.githubusercontent.com/31089228/72238091-bcecba80-3617-11ea-991b-c32445bdf762.png)
当点击 
![image](https://user-images.githubusercontent.com/31089228/72238097-c544f580-3617-11ea-9861-e792480c1daf.png) bu f部分改变RGBA后 所有内容均正常

**Comment by StringKe** [comment]
https://github.com/xiaokaike/vue-color/blob/ab3399a90e5e5ce2013351c785bdbcc17af2bc5c/src/mixin/color.js#L46
预计此处 toRgb 无法转换

**Comment by StringKe** [comment]
如果默认的颜色是 白色 或者 黑色就会出现这个问题，仓库demo

**Comment by linx4200** [comment]
您好，这是符合预期的行为。

因为您拖动改变的是颜色的 [色相Hue](https://baike.baidu.com/item/%E8%89%B2%E7%9B%B8)
![image](https://user-images.githubusercontent.com/3954517/75297796-be8edc80-586b-11ea-9fbf-cea034f141a2.png)

黑色或白色因为他们的饱和度、亮度都已经为 0 了，因此改变色相是没有任何效果的。

因此这个组件如果是黑色或白色的值，需要配合被您隐藏了的饱和度选择器来修改：
![image](https://user-images.githubusercontent.com/3954517/75298026-58568980-586c-11ea-9d50-ca152eb8a8c2.png)
