### ISSUE TITLE
How to Limit color options for slider?

### ISSUE THREAD

**Issue by L-K-Mist** [xiaokaike/vue-color#199]
I need to limit the range of colors offered to the user in a slider.
I know you offer such with the pickers, but not as far as I can see for the slider.

Is there any way that I can make this happen?  Even by climbing into your code?

Any pointers if I try?

Here's what I need to produce.  The Button part is easy, but the limited range is tricky and I don't see any obvious alternatives.

![range color](https://user-images.githubusercontent.com/22072669/78469380-ef8ee680-7720-11ea-9e97-52d046429459.png)

**Comment by linx4200** [comment]
Sorry, we don't have such component for now. And we tend to provide standard and commonly used color pickers.
