### ISSUE TITLE
How to change css files of the library?

### ISSUE THREAD

**Issue by kentforth** [xiaokaike/vue-color#205]
**How can I change css rules of any of selectors in css files in the library?**
For example: I have Photoshop picker and I want to change color oh the header "Color Picker" to another color
**Where can I do that?**

**Comment by b-karin** [comment]
**In your parent component**, you can simply reassign the values by using css specificity, e.g.:
`
<style lang="stylus">
.colorPicker
  & .vc-compact
    padding-top 25px // initial value was 5px
    padding-left 25px // initial value was 5px
</style>
`
To find css classes that you need you can take a look at the initial component's sources
