### ISSUE TITLE
2.7.1 in not published to npmjs.com?

### ISSUE THREAD

**Issue by veredcon** [xiaokaike/vue-color#216]
Hi,

I was trying to install vue-file-toolbar-menu and it seed to require vue-color 2.7.1. 
I cannot install 2.7.1:

![image](https://user-images.githubusercontent.com/9718939/98818269-fce91d80-2433-11eb-8f3a-fda9896605f4.png)

Seems like 2.7.0 is the last one available?
![image](https://user-images.githubusercontent.com/9718939/98818298-05d9ef00-2434-11eb-9462-0993f9651499.png)

Could you please advise?
Thanks

**Comment by linx4200** [comment]
I think `v2.7.1` is on npm, please try again.

https://www.npmjs.com/package/vue-color/v/2.7.1
