### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by luckyasme** [xiaokaike/vue-color#217]
when i moved mouse pointer to choose color, the cosole printed an error。。。

![1111](https://user-images.githubusercontent.com/48974807/99161988-273c2300-2733-11eb-9926-6f185944f224.png)

😂
so how can i fix it...

**Comment by linx4200** [comment]
Hello @luckyasme . Please provide a online reproduction or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
