### ISSUE TITLE
Issue in Saturation component : Cannot read property 'clientWidth' of undefined

### ISSUE THREAD

**Issue by lk77** [xiaokaike/vue-color#220]
Hello,

this is a follow up of https://github.com/xiaokaike/vue-color/issues/119

I have an issue in my app, when hitting delete key (which remove the picker in my use case) and changing color in the picker at the same time, it produces an error :
```
Cannot read property 'clientWidth' of undefined
```

it's an edge case, but it does happen sometimes in production, it does not have any real visible consequence, just an error in the console. 

reproduction : 

https://jsfiddle.net/lk77/oz46nyvd/

Reproduction video

https://user-images.githubusercontent.com/9606882/103014630-62eeb780-453f-11eb-8356-7b03665adf6c.mp4

thanks.

**Comment by linx4200** [comment]
Hi @lk77 2.8.1 has fixed this issue.

**Comment by lk77** [comment]
Thanks !
