### ISSUE TITLE
Usage Docs not clear

### ISSUE THREAD

**Issue by alfligno** [xiaokaike/vue-color#223]
It is not clear to me on how do I import the ```swatches-picker``` well in fact the import should be `import { Photoshop } from 'vue-color'`

Also I did tried

```
import Vue from 'vue'
import { Photoshop, swatches } from 'vue-color'

Vue.component('swatches-picker', swatches);
```

but no luck, Can you make it clear to the reader on how to properly use its sub component? specially for beginners

**Comment by alfligno** [comment]
Got it working now it should be `import { Swatches } from 'vue-color'` *s* should be uppercase

**Comment by wucyAAA** [comment]
@alfligno thanks you a lot
