### ISSUE TITLE
move at bottom, circle jump

### ISSUE THREAD

**Issue by Helloooooooooo** [xiaokaike/vue-color#25]
![1](https://cloud.githubusercontent.com/assets/15864811/20516902/bcff1800-b0d3-11e6-96f7-2b988877c2af.gif)

**Comment by xiaokaike** [comment]
what system and browser?

**Comment by Helloooooooooo** [comment]
win10
This problem exists at Chrome/55.0.2883.28,    Firefox/47.0,    Edge

**Comment by m00nk** [comment]
The same issue in Chrome 56.0.2924.76 on Linux

**Comment by cassioscabral** [comment]
I'm taking a look at this. There is a value HSV sent to tinycolor, when you hit the bottom, V will be zero. If you create a tinycolor object like `tinycolor({h: 130, s: 60, v: 0})` it will have a value hex of `#000000`(same for HSV and all the others) i.e. turns to black. So the UI will update to that new color making the circle jump to match the new color.

**Comment by cassioscabral** [comment]
This is a known issue on TinyColor and I'm still looking into it how to avoid that kind of jump. 
https://github.com/bgrins/TinyColor/issues/86
