### ISSUE TITLE
Somes bugs

### ISSUE THREAD

**Issue by YoannMa** [xiaokaike/vue-color#31]
Hi, 

I have found somes bugs and I've tried some trick to be able to solve these problems : 

## 1 - hueSlider unable to move

When you select a color with a `hsv.s = 0` (black to white) with the `saturationPicker` you can move the `hueSlider`

```javascript
// inside the mixin's function _colorChange

let hexColor = color.toHexString().toUpperCase();

// handle hueSlider unable to move when the color is black or white (1)
if (hexColor == '#FFFFFF' || hexColor == '#000000') {
    hsl.h = data.h || oldHue || hsl.h;
    hsv.h = data.h || oldHue || hsl.h;
    //      given  or   old  or  new
}
```

## 2 - hueSlider doesn't give full spectrum

HueSlider on the right/top stop at `359` of hue instead of `360` (giving a `#FF0004` instead of `#FF0000`).

And when i tried to change this, i added this to avoid moving to an 0 hue when you are at the end of the spectrum.

```javascript
// inside the mixin's function _colorChange

let hexColor = color.toHexString().toUpperCase();

// when the color hue is red, handle red color rotation on hueSlider
// (avoid doing left to right when red color is modified) (2)
if (hsl.h == 0) {
    hsl.h = ((data.h || oldHue) > 180 ? 360 : 0) || hsl.h;
    hsv.h = ((data.h || oldHue) > 180 ? 360 : 0) || hsl.h;
}
```

## 3 - The #25 bug

The behaviors comes from 2 problem : 

### Percentage

Using a percentage with the `saturationPicker` provoke some problems with tinycolor when `hsv.v` and `hsv.s` are `>= 1` because tinycolor will interpret that as `100%` instead of `1%`

It causes the vertical shift when `hsv.v` is  `>= 1` and an horizontal shift when `hsv.s` is  `>= 1`
It won't happend every time, but more the saturationPicker is large more the bug will appear.

Using 0-1 ratio solve the problem : 

```javascript
// saturationPicker handleChange function
this.onChange({
    h      : this.colors.hsl.h,
    s      : left / containerWidth,
    v      : -(top / containerHeight) + 1,
    a      : this.colors.hsl.a,
    source : 'rgb'
});
```

```javascript
pointerTop() {
    return (-(this.colors.hsv.v) + 1) * 100 + '%';
},
pointerLeft() {
    return this.colors.hsv.s * 100 + '%';
}
```
I think you should change every percentages to a ratio to avoid this problem in the futur.

And to make it more robust you could even use `tinycolor.fromRatio(color)` instead of `tinycolor(color)` when using ratio.

### Horizontal Shift

This one is more tricky to find, it happends when the `hsv.v` is `<= 10%` and the result is that the `hsv.s` change following Tinycolor `hsv.s` value instead of cursor value.

```javascript
// inside the mixin's function _colorChange
// i added oldColor as reference to the old this.colors as parameters of the function

let hexColor = color.toHexString().toUpperCase();
// when the color is nearly black, avoid getting position bug in the saturationPicker (3)
if (hsv.v <= 0.1) {
    hsv.s = data.s || oldColor.hsv.s || hsv.s;
    hsv.v = data.v || oldColor.hsv.v || hsv.v;
    //      given  or      old       or   new
}
```

## 4 - 5 Color Slider

Not sure if it's a bug but the last color of slider component (the 5 colors one) doesn't scale when it's selected (it does when the 1-4 are selected)

**Comment by YoannMa** [comment]
I found out that my solutions wasn't updated.

## 1 - hueSlider unable to move

Updated solution :

```javascript
// handle hueSlider unable to move when the color is black or white
if (hsv.s == 0) {
    hsl.h = data.h || oldHue || hsl.h;
    hsv.h = data.h || oldHue || hsl.h;
    //      given  or   old  or  new
}
```

3 - The #25 bug

### Horizontal Shift

And the Horizontal Shift problem doesn't need the `oldColor` : 

```javascript
// when the color is nearly black, avoid getting position bug in the saturationPicker
if (hsv.v <= 0.1) {
    hsv.s = data.s || hsv.s;
    hsl.s = data.s || hsl.s;
    //      given  or  new
}
```

**Comment by linx4200** [comment]
@YoannMa Thanks for your super helpful information.

These problems have been fixed. Please upgrade to latest version.

**Comment by YoannMa** [comment]
:+1: Thanks for the update, I'm glad I could help
