### ISSUE TITLE
在 hex 模式下，拖动透明度滑动条并没有效果

### ISSUE THREAD

**Issue by think2011** [xiaokaike/vue-color#32]
除了 HEX 格式，其他格式拖动透明度滑动条是有效的，但是想要的是拖动透明度后hex的值。

**Comment by xiaokaike** [comment]
hex 值是无透明度维度的，修改了透明度，hex也不会变化

**Comment by think2011** [comment]
![image](https://cloud.githubusercontent.com/assets/3961388/21561582/3e926ce4-cea9-11e6-8f45-73c5754696b7.png)
恩，我明白了，可是我用的是chrome picker样式。 
上面的截图是chrome的picker，是有效果的。

如果chrome picker拖动却没有效果的话，应该在hex模式下去掉这个无效的功能。

**Comment by think2011** [comment]
或者像是chrome的那样从hex自动切换成RGBA模式，希望能够改进一下。

**Comment by xiaokaike** [comment]
好的
