### ISSUE TITLE
not support ontouch

### ISSUE THREAD

**Issue by yybawang** [xiaokaike/vue-color#33]
我想用在手机端，却发现点不动

**Comment by cassioscabral** [comment]
The direct translation by Google is: 
I want to use the phone side, but found that the point does not move. 

I will put this on my TODO list

**Comment by linx4200** [comment]
@yybawang 你好，请问是在什么手机，什么浏览器上点不动呢？

**Comment by julianfox** [comment]
Any update about it?

**Comment by linx4200** [comment]
@julianfox Sorry for the delay. Which component does not function properly in mobile device? Could you provide more information about it?

**Comment by peefly** [comment]
The saturation-pointer is not draggable on my Pixel 2 (Chrome 63, Android 8.1), although I can still use single touch to set the color.

**Comment by linx4200** [comment]
@peefly Thanks for your feedback, I will look into it asap.

**Comment by julianfox** [comment]
@peefly same problem on my Iphone SE (safari)

**Comment by Ben-Mack** [comment]
Yes, please add support for touch drag on main saturation area, this is the only point left to make this the best color picker for Vue.

**Comment by linx4200** [comment]
Hey guys! This feature is finally supported in `2.4.4` ! Please update to use it.  Thanks!
