### ISSUE TITLE
_c is not defined , 请帮忙看是什么问题。

### ISSUE THREAD

**Issue by gani10** [xiaokaike/vue-color#34]
![4479d665-512f-46da-9e9a-6b8b1cae8049](https://cloud.githubusercontent.com/assets/19661052/21610056/def3fe1e-d200-11e6-9a92-8f8f5819c4fb.png)

<img width="1386" alt="d3c8279e-b071-47c4-9bd4-29bfe5999b2d" src="https://cloud.githubusercontent.com/assets/19661052/21609395/28649df0-d1fd-11e6-9263-62c6b4aaebeb.png">

**Comment by gani10** [comment]
使用方式上有错误吗？请指点怎么使用。。谢谢

**Comment by xiaokaike** [comment]
有错，vue的基本用法都错了。

```js
new Vue({
el: '#wrap'
})
```

#wrap 都不存在

**Comment by gani10** [comment]
在body下是有<div id="wrap">这个代码，为了给你看的简便，罗列代码的时候去掉了而已。
也就是说加上去了报同样的错误。

**Comment by Flavioamorim** [comment]
I am with same erro, please help me with solution

**Comment by kibray** [comment]
I am in the same situation and I have also another error in console:
`[Vue warn]: Error when rendering component <Sketch>:  vue.min.js:2574`

Can anyone help me with that, please?

**Comment by Flavioamorim** [comment]
i fix my error with a new instalattion of vue.

**Comment by kibray** [comment]
Which version of Vue are you using? mine is 2.0.1

**Comment by Flavioamorim** [comment]
i am  using "vue": "^2.1.0", and this plugin working fine

**Comment by kibray** [comment]
Thank you very much @Flavioamorim I solved too, my Vuejs was too old. You made my day :D 
By the way...eu moro em BH também!!

**Comment by Flavioamorim** [comment]
this is my example: https://github.com/Flavioamorim/vue-with-vue-color
