### ISSUE TITLE
遇到个undefined的bug

### ISSUE THREAD

**Issue by yelingfeng** [xiaokaike/vue-color#35]
![image](https://cloud.githubusercontent.com/assets/1932350/21635672/e9f85050-d299-11e6-9130-59b1ae763ff4.png)

环境是  
elementUI  1.1.2 
vue  2.1.8

目前还没找到原因

**Comment by miloandco** [comment]
I have this issue too.

**Comment by yelingfeng** [comment]
貌似vue 2.1.8的问题 切换回2.1.6 但是我启vue-color 本地工程 没啥问题

**Comment by m00nk** [comment]
I see the same bug. On the demo site the HTML-code of the color pointer is 

```html
<div class="vue-color__saturation--pointer">
      <div class="vue-color__saturation--circle"></div>
</div>
```

but in my code that HTML is

```html
<div class="vue-color__saturation--pointer">
      undefined
</div>
```

Please, fix this bug. Thank you.

**Comment by m00nk** [comment]
The bug is still not fixed (I have tested 2.0.4 version).

![_002](https://cloud.githubusercontent.com/assets/516574/21906926/6604da12-d91e-11e6-8f10-a404169626a1.png)

**Comment by zhex** [comment]
The bug is still in 2.0.4 in NPM

**Comment by xiaokaike** [comment]
update to 2.0.5
