### ISSUE TITLE
.container class conflicts with twitter-bootstrap

### ISSUE THREAD

**Issue by antongorodezkiy** [xiaokaike/vue-color#4]
Thanks for the lib!

Just for information, `.container` class conflicts with twitter-bootstrap's `.container` class. This could be fixed through css, but maybe you could just change it's name in future for something more specific, like `.vue-color-container` or something.

![screenshot-dev 3101 2016-05-19 22-43-08](https://cloud.githubusercontent.com/assets/580599/15407377/33097922-1e13-11e6-96ee-7b3f486f70f9.png)

**Comment by xiaokaike** [comment]
ok 
update you vue-color version to 0.0.5.
I change `.container` to `.vc-container`

**Comment by antongorodezkiy** [comment]
thanks!
