### ISSUE TITLE
Can not set opacity to zero

### ISSUE THREAD

**Issue by m00nk** [xiaokaike/vue-color#41]
The minimal opacity that I can set with the slider is 0.01. If I move slider to the left edge it jumps to the maximum (1.0).

Also when I try to enter 0 to the "A" field the value changes to "1".

**Comment by linx4200** [comment]
Fixed. Please upgrade to latest version.

**Comment by wLove-c** [comment]
The minimal opacity that I can set with the slider is 0.01. If I move slider to the left edge it jumps to the maximum (1.0).

when I try to enter 0 to the "A" field the value changes to "0", but I get the value also is no opacity;
![image](https://user-images.githubusercontent.com/24515513/57426306-3d6d4700-7251-11e9-8c0c-3cf59fb5bc16.png)

` <div>
    <sketch-picker
      v-model="pickerColor"
      @input="updateValue"/>
  </div>`

`data () {
    return {
      pickerColor: '#ffffff'
    }
  },`
