### ISSUE TITLE
jquery required?

### ISSUE THREAD

**Issue by Towerful** [xiaokaike/vue-color#43]
Hello,
after using `yarn add vue-color`
and 
``` js
import {Compact} from 'vue-color';
import Vue from 'vue';
Vue.component('v-color-picker', Compact);
```
I am receiving the follwoing webpack error 
```
              ERROR  Failed to compile with 1 errors

This dependency was not found in node_modules:

* jquery
```

I tried importing it into a component - as opposed to registering it as a global component - and received the same issue.

I've searched the `/node_modules/vue-color/`, and the only references to `jquery` are in comments about functions.  I checked `tinycolor2` and `material-colors` and cannot find a reference for jquery.

I've looked through the package, and it is installing version 2.0.5.

Using `laravel`'s default `mix` webpack config.

This is very baffling!

**Comment by Towerful** [comment]
running `yarn add jquery` solves this, obviously.

**Comment by xiaokaike** [comment]
with no need for jquery
