### ISSUE TITLE
Dependency failures in v2.0.6

### ISSUE THREAD

**Issue by Repox** [xiaokaike/vue-color#48]
Fresh installation, following the instructions, starting with running:

    $ npm install vue-color

Adding the following to my JS:

    var Photoshop = require('vue-color/src/Photoshop.vue');

results in the following, when running `$ npm run dev`:

    This dependency was not found:
    
    * vue-color/src/Photoshop.vue in ./resources/assets/js/app.js

Alright, looking into the directory structure shows that `Photoshop.vue` now resides in `vue-color/src/components/` so I'll try and reference that one, and this results in the following, when running `$ npm run dev`:

    This dependency was not found:
    
    * !!vue-style-loader!css-loader!../../../vue-loader/lib/style-rewriter?id=data-v-6d2f99f6!stylus-loader?paths[]=node_modules!../../../vue-loader/lib/selector?type=styles&index=0!./Photoshop.vue in ./~/vue-color/src/components/Photoshop.vue

**Comment by cassioscabral** [comment]
Yeah, that is not going to work, you are using require in a ES6 module export. Shouldn't work. 

Could you try to do this suggested in this issue: https://github.com/xiaokaike/vue-color/issues/16

```js
var VueColor = require('vue-color');

components: {
  'photoshop-picker': VueColor.Photoshop
 }

```

Checking the dist file this is what I saw:

```js
	var VueColor = {
	  version: '1.0.26',
	  Compact: _Compact2.default,
	  Material: _Material2.default,
	  Slider: _Slider2.default,
	  Swatches: _Swatches2.default,
	  Photoshop: _Photoshop2.default,
	  Sketch: _Sketch2.default,
	  Chrome: _Chrome2.default,
	  Alpha: _Alpha2.default,
	  Checkboard: _Checkboard2.default,
	  EditableInput: _EditableInput2.default,
	  Hue: _Hue2.default,
	  Saturation: _Saturation2.default,
	  ColorMixin: _color2.default
	};

	module.exports = VueColor;
```

I'm not familiar with require, was using import all the time and couldn't notice this issue. Probably is just the example that is wrong and should be fixed in a minute.

**Comment by Repox** [comment]
Gave up eventually and found another solution.

**Comment by nhayder** [comment]
@Repox hey what is the solution that worked for you, can you share a link for the component because it looks like vue-color is not getting installed on my app.
