### ISSUE TITLE
Class Name Conflicts

### ISSUE THREAD

**Issue by frankdugan3** [xiaokaike/vue-color#5]
Given that the class names for the color picker styling have pretty generic terms (`input` for example), and that the style is not scoped, the classes conflict with existing classes when vue-color is used in a different project.

I like it being unscoped, because that makes it easy to override classes as needed. But I would suggest using a naming convention that prefixes each class with `vue-color` so that they will be unlikely to clash with existing classes in other projects.

If you would like, I could make the changes and submit a pull request.

**Comment by xiaokaike** [comment]
thinks  just do it

**Comment by frankdugan3** [comment]
Submitted pull request: https://github.com/xiaokaike/vue-color/pull/6

**Comment by xiaokaike** [comment]
merge  but  your code has some problem in  (Saturation.vue)[https://github.com/frankdugan3/vue-color/blob/master/src/components/common/Saturation.vue#L2]

**Comment by frankdugan3** [comment]
Whoops, sorry for missing that.
