### ISSUE TITLE
Getting error in the console.

### ISSUE THREAD

**Issue by rajeshwar-fissionhq** [xiaokaike/vue-color#51]
Getting an error in the console, when we open the page, where we are using this color picker.

```
[Vue warn]: existing instance property "fields" will be overwritten by a computed property with the same name. 
(found in component <Chrome>)
```
![screen shot 2017-03-30 at 12 20 22 pm](https://cloud.githubusercontent.com/assets/11268935/24491100/49133654-1543-11e7-9920-d02ee7a132d0.png)

**Comment by xiaokaike** [comment]
fix

**Comment by rajeshwar-fissionhq** [comment]
Is it fixed @xiaokaike ?
