### ISSUE TITLE
Default Color

### ISSUE THREAD

**Issue by SmartWeb25** [xiaokaike/vue-color#55]
Need to set default color easily.

**Comment by linx4200** [comment]
@SmartWeb25   Do you have any suggestion?  May I know what is the best way to set default color in your mind?

**Comment by linx4200** [comment]
The default colors can be customized now! Please upgrade to the latest version. And the usage is down blow:

```html
/* presetColors accepts an array of colors */
<sketch v-model="colors" :presetColors="presetColors"></sketch>
```

And the document will catch up sooooooon!

Thanks for your patience!
