### ISSUE TITLE
Unable to drag the slider if the default hex color is touching the left border

### ISSUE THREAD

**Issue by rajeshwar-fissionhq** [xiaokaike/vue-color#61]
When i set the default hex color is touching the left borders. The slider below the color picker is not sliding, but the opacity slider is working fine. It is also the case with all the colours, which are touching the left borders. Please have a look at the attached screenshots.

![screen shot 2017-05-08 at 12 01 03 pm](https://cloud.githubusercontent.com/assets/11268935/25792748/262a585e-33e6-11e7-85e5-ce3d67530507.png)
![screen shot 2017-05-08 at 12 00 52 pm](https://cloud.githubusercontent.com/assets/11268935/25792749/26479bc6-33e6-11e7-997e-af03f4c61cbe.png)
![screen shot 2017-05-08 at 12 00 31 pm](https://cloud.githubusercontent.com/assets/11268935/25792750/264ba630-33e6-11e7-8fab-f240bd05e69f.png)
![screen shot 2017-05-08 at 12 02 26 pm](https://cloud.githubusercontent.com/assets/11268935/25792758/3a233dc6-33e6-11e7-8640-13f8d4a8e0f8.png)

**Comment by rajeshwar-fissionhq** [comment]
Even in the demo link, it is not moving the slider, if we select the color #fff.
![screen shot 2017-05-16 at 12 07 13 pm](https://cloud.githubusercontent.com/assets/11268935/26092745/45af0bf2-3a30-11e7-8118-fb113b74670a.png)

**Comment by donnysim** [comment]
👍

**Comment by linx4200** [comment]
fixed. please upgrade to 2.2.1
