### ISSUE TITLE
v-model for "default props"?

### ISSUE THREAD

**Issue by defaye** [xiaokaike/vue-color#62]
I'm just curious why you're using `v-model`for default properties instead of using `v-bind` instead? I would have thought that using `v-model` implies a two-way update to the value, but that's not the case here. We're using `@change-color` to effect a manual update to our model, right? Why did you make it this way? I need some help to understand your reasoning behind this as I find it a little confusing.

**Comment by xiaokaike** [comment]
https://github.com/xiaokaike/vue-color/pull/58/files

**Comment by defaye** [comment]
What is this supposed to show? Some context with your response please?

What I'm trying to say is that you are using `v-model="mymodel.color"` for a component when it appears that when the colour is changed, the expecting behaviour of a `v-model` would be to automatically update the value of `mymodel.color`. This doesn't happen. Instead, you have the `onChange` event. What is the point of using `v-model` if it isn't syncing the changes automatically? Or am I missing something here?

**Comment by xiaokaike** [comment]
It is a design bug,  I update the project, You can use like this:

auto update 
```html
<material-picker v-model="colors" />
```
or update by youself 

```html
<material-picker :value="colors" @input="updateValue" />
```

just like <input>

**Comment by nerdyglasses** [comment]
@xiaokaike good job 😘
