### ISSUE TITLE
How to Disable some colors?

### ISSUE THREAD

**Issue by MateusSilveira98** [xiaokaike/vue-color#63]
I need disable dark colors in my colorpicker, i'm using the "Compact" colorpicker, How can i disable the dark colors?

**Comment by MateusSilveira98** [comment]
So, can not define what colors I want?

**Comment by dolbex** [comment]
Just as a heads up I'm cutting off the top half of my picker utilizing CSS (I need dark colors only)

**Comment by linx4200** [comment]
The colors in Compact component can be customize now! Please upgrade to the latest version. And the usage is down blow:

```html
/* palette accepts an array of colors */
<compact v-model="colors" :palette="palette"></compact>
```

And the document will catch up sooooooon!

Thanks for your patience!
