### ISSUE TITLE
Chrome hex input

### ISSUE THREAD

**Issue by runrog** [xiaokaike/vue-color#65]
Not sure if this is an issue but more of a question. Is there any way to disable the autocomplete on keyup of the hex value input for the chrome picker? It's almost more of an inconvenience.

**Comment by mirshko** [comment]
I am also having a poor UX with this issue. Its jumping to colors as I'm inputting them, which I do not want.

![kapture 2017-05-22 at 18 55 46](https://cloud.githubusercontent.com/assets/8116716/26331696/5050e086-3f20-11e7-81d6-ffc2defb6b55.gif)

**Comment by runrog** [comment]
One small workaround is that you can paste full hex values in there. It's just when you try to enter them manually. This is super annoying for users who know values by memory.

**Comment by mirshko** [comment]
@xiaokaike any ETA on a fix for this?

**Comment by 304NotModified** [comment]
We are also looking for a fix for this. Just make it an option to disable the autocomplete.

**Comment by ststaynov** [comment]
+1

**Comment by runrog** [comment]
I submitted a fix for this, hopefully it gets merged
https://github.com/xiaokaike/vue-color/pull/70

**Comment by xiaokaike** [comment]
npm update to  `v2.2.0`
