### ISSUE TITLE
Vue 2.0 Compatibility

### ISSUE THREAD

**Issue by Towerful** [xiaokaike/vue-color#7]
Hello,
Love this plugin!   
But there is currently an issue with Vue 2.0 Compatibility. 

```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "colors" (found in component: <swatches>)  

[Vue warn]: data-pick="{{pick}}": Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.  

[Vue warn]: data-color="{{c}}": Interpolation inside attributes has been deprecated. Use v-bind or the colon shorthand instead.
```

Simply used in a Vue 2.0 component as follow:    
`<swatches :colors="color"></swatches>`

First issue would be resolved by raising an event within the `src/mixin/color.js` lines 38 & 42.  
Users would then need to subscribe to this using something like `@pick="updateColor"`

Second issue would be resolved by using `:data-pick="pick"` instead of `data-pick="{{pick}}"`, line 2 of `src/components/Swatches.vue`.  
I imagine there would be other issues in the other components, however I am only using swatches.

Third issue is similar to the Second issue, however located on line 6 of `src/components/Swtaches.vue`

I would make a pull request, or whatever, but I am hopeless with git :)

**Comment by Towerful** [comment]
Looking through the other components, the `:colors.sync` issue is quite prevalent.  
As Vue 2.0 is still alpha, it's probably worth watching at the ecosystem of components, and what the 'standard way' of dealing with synchronous props is going to be.

I think it will look like:
```
props: ['colors'],
computed: {
    value: {
        get(){
            return this.colors;
        },
        set(newVal) {
            this.$emit('change', newVal);
            return newVal;
        }
    }
}
```

I think this is quite clunky, however, as it is relying on the parent component to propagate that change back round to `colors`

perhaps something like this:  
```
props: ['colors'],
data() {
    return {
        _value: this.colors
    }
},
watch: {
    colors(newVal) {
        this._value = newVal;
    }
},
computed: {
    value: {
        get(){
            return this._value;
        },
        set(newVal) {
            this._value = newVal
            this.$emit('change', newVal);
        }
    }
}
```

Unfortunately, this is a lot of boilerplate, but it allows for an internal shadow copy that will track the supplied props, and allow direct mutation

**Comment by Towerful** [comment]
Seems like in Vue 2.0, `v-model` can be used on components
```
<swatches v-model="something.color"></swtaches>
{
    props: ['value'], //instead of colors
}
```

**Comment by xiaokaike** [comment]
thanks, i will update to support vue2.0 soon

**Comment by CinKon** [comment]
Any Progress? :)

**Comment by kristjanjansen** [comment]
Any update on this?

**Comment by xiaokaike** [comment]
support in  next branch  https://github.com/xiaokaike/vue-color/tree/next

**Comment by yelingfeng** [comment]
@xiaokaike  hi man  , how long will coming about vue2.0 branch  ? i want use next branch now , how about it is stable ?

**Comment by xiaokaike** [comment]
support vue 2.0 and publish to npm
