### ISSUE TITLE
Not working when updating from 2.0.7 to 2.2.0

### ISSUE THREAD

**Issue by Tlapi** [xiaokaike/vue-color#73]
There is no error but the picker is not working and not displaying correctly.

<img width="174" alt="snimek obrazovky 2017-06-13 v 16 49 35" src="https://user-images.githubusercontent.com/2815391/27088570-550e9138-5058-11e7-9056-e8f5f14d4c6b.png">

Any idea why?

Going back to 2.0.7 works good.

**Comment by Tlapi** [comment]
I was not even able to get the latest version running inside our Vue app or running `npm run dev` command with clean clone of this repository ;-(

**Comment by linx4200** [comment]
@Tlapi  Sorry for the delayed response. Could you provide more information about your problems?
For example, What did the command line tool show when you run `npm run dev`.

**Comment by linx4200** [comment]
Further information required. Would reopen this issue.
