### ISSUE TITLE
How i use RGBA as final value like rgba(0,0,0,0.5) ? 

### ISSUE THREAD

**Issue by overallduka** [xiaokaike/vue-color#74]
I want in my v-model to have raw final value like `rgba(0,0,0,0.5)`..by now is returning the object in my model and is weird. Have some configuration or adjusts can be made to work like this ? Thanks a lot. I love the picker.

**Comment by linx4200** [comment]
The object in the model has everything you need to concatenate the `rgba` string. Out of concern for flexibility, we would remain the current object in model.
Please use computed properties to achieve your purpose.
