### ISSUE TITLE
style class conflicts with css library

### ISSUE THREAD

**Issue by elvisyang2016** [xiaokaike/vue-color#82]
I uses bulma as my project global css library. Bulma has a style class named 'container'. 
And the src/components/common/Hue.vue also use 'container' as a style class. Then the two sliders on the Chrome/Sketch palettes are abnormal. when moving the alpha slider to the right end side, the value is not 1, just about 0.11.
I suggest to change the style class 'container' to something else not so commonly.

**Comment by brunoeris** [comment]
Same here, bootstrap has a style class named 'container' too.

**Comment by linx4200** [comment]
Fixed. Please upgrade to the latest version. Thanks for your support.
