### ISSUE TITLE
[EditableInput.vue] [Vue warn]: Computed property "val" was assigned to but it has no setter

### ISSUE THREAD

**Issue by excaliburhan** [xiaokaike/vue-color#83]
`Vue2.4.2` added a limit for computed property, see [assigning to a computed property without setter does not fail](https://github.com/vuejs/vue/issues/6078)

So we need to change `v-model="val"` to `:value="val"` and handle the update by `input event` which is already done. I tested locally , it works and the warning disappears.

Please fix it asap, thanks.

**Comment by linx4200** [comment]
Fixed. Please upgrade to the latest version.
