### ISSUE TITLE
[Vue warn]: The computed property "fields" is already defined in data.

### ISSUE THREAD

**Issue by cde06** [xiaokaike/vue-color#84]
When I instanciate the 'Chrome' component from 'vue-color' on chrome debuger I've got the following warning:  
[Vue warn]: The computed property "fields" is already defined in data.

**Comment by linx4200** [comment]
I can't reproduce with vue-color version 2.3.3, could you upgrade to the latest version and have another try? Or is it possible to provide more info about your problem, for example, the versions of Vue?

**Comment by cde06** [comment]
I've open the ticket based on the 2.3.1 and I still encounter the same issue with the release 2.3.2. 
it's seems that 2.3.3 is not yet released.

**Comment by linx4200** [comment]
@cde06 sorry, its 2.3.2. But I still can't reproduce. Could you give a demo of your usage and your version of vue? Thanks.

**Comment by C-aptain** [comment]
Same issue here.
```
"vue": "^2.3.3",
"vue-color": "^2.4.2",
"webpack": "^2.6.0",
```
Usage:
```
<template>
  <div>
    <chrome :value="color"></chrome>
  </div>
</template>

<script>
import {Chrome} from 'vue-color'

export default {
  components: {
    Chrome,
  },
  data() {
    return {color: '#fff'}
  },
}
</script>
```

**Comment by maxxscho** [comment]
Same here

**Comment by linx4200** [comment]
@maxxscho  @C-aptain  I’d like the exact version number to help reproduce.  Thanks.

**Comment by maxxscho** [comment]
@linx4200 2.4.2

**Comment by linx4200** [comment]
@maxxscho  what about vue and webpack?

**Comment by maxxscho** [comment]
@linx4200 Webpack 3.8.1, Vue 2.5.3

**Comment by linx4200** [comment]
I still can't reproduce. And after google for this warning, most situations are caused by a package named 'vee-validate'. Maybe you guys are using it which could config fieldBagName to solve the conflict, see [here](http://vee-validate.logaretm.com/#configuration).

**Comment by maxxscho** [comment]
@linx4200 In my case this is the solution 👍  Thx man!!! I didn't think vee-validate could be the problem 🙂

**Comment by linx4200** [comment]
Glad I can help 😄
