### ISSUE TITLE
sketch 没有自定义事件吗

### ISSUE THREAD

**Issue by chenyihao2621023** [xiaokaike/vue-color#85]
如像Photoshop 中的 @ok 或 @cancle 或者 有什么替代的实现方式呢？

**Comment by linx4200** [comment]
请问 sketch 需要什么自定义事件呢？

**Comment by chenyihao2621023** [comment]
比如onchange事件

**Comment by linx4200** [comment]
明白你的意思了，暂时没有实现，欢迎提 PR. ; ]

**Comment by linx4200** [comment]
`<sketch-picker :value="colors" @input="updateValue"></sketch-picker>`

`@input` 中可以获取到变化后的色值。
