### ISSUE TITLE
I have an error. 'Cannot read 'hsv' of undefined'

### ISSUE THREAD

**Issue by zkils** [xiaokaike/vue-color#86]
My code..

<color-picker v-model="colors"></color-picker>

...

<script>
 import { Sketch } from 'vue-color'

...
 components: {
'colorPicker' : Sketch
}

data () {
      return {
        colors:  {
          hex: '#194d33',
          hsl: {
            h: 150,
            s: 0.5,
            l: 0.2,
            a: 1
          },
          hsv: {
            h: 150,
            s: 0.66,
            v: 0.30,
            a: 1
          },
          rgba: {
            r: 25,
            g: 77,
            b: 51,
            a: 1
          },
          a: 1
        },
}

...

Cannot read property 'hsv' of undefined
    at VueComponent.bgColor (vue-color.min.js:1)
    at Watcher.get (vue.runtime.common.js:2934)
    at Watcher.evaluate (vue.runtime.common.js:3042)
    at VueComponent.computedGetter [as bgColor] (vue.runtime.common.js:3240)
    at Object.get (vue.runtime.common.js:1482)
    at Proxy.r (vue-color.min.js:1)
    at VueComponent.Vue._render (vue.runtime.common.js:2216)
    at VueComponent.updateComponent (vue.runtime.common.js:2609)
    at Watcher.get (vue.runtime.common.js:2934)
    at new Watcher (vue.runtime.common.js:2926)

**Comment by linx4200** [comment]
```html
<sketch-picker v-model="colors"></sketch-picker>
```

Please make sure pass the `colors` as the component's `v-model`

**Comment by zzzzzyb** [comment]
[Vue warn]: Error when rendering component <Saturation> at src/components/common/Saturation.vue: 
warn @ vue.common.js?e881:519
Vue._render @ vue.common.js?e881:2959
(anonymous) @ vue.common.js?e881:2189
get @ vue.common.js?e881:1652
Watcher @ vue.common.js?e881:1644
Vue._mount @ vue.common.js?e881:2188
Vue$3.$mount @ vue.common.js?e881:5978
Vue$3.$mount @ vue.common.js?e881:8305
init @ vue.common.js?e881:2500
createComponent @ vue.common.js?e881:4052
createElm @ vue.common.js?e881:3995
createChildren @ vue.common.js?e881:4103
createElm @ vue.common.js?e881:4028
createChildren @ vue.common.js?e881:4103
createElm @ vue.common.js?e881:4028
patch @ vue.common.js?e881:4446
Vue._update @ vue.common.js?e881:2215
(anonymous) @ vue.common.js?e881:2189
get @ vue.common.js?e881:1652
Watcher @ vue.common.js?e881:1644
Vue._mount @ vue.common.js?e881:2188
Vue$3.$mount @ vue.common.js?e881:5978
Vue$3.$mount @ vue.common.js?e881:8305
init @ vue.common.js?e881:2500
createComponent @ vue.common.js?e881:4052
createElm @ vue.common.js?e881:3995
createChildren @ vue.common.js?e881:4103
createElm @ vue.common.js?e881:4028
patch @ vue.common.js?e881:4446
Vue._update @ vue.common.js?e881:2215
(anonymous) @ vue.common.js?e881:2189
get @ vue.common.js?e881:1652
Watcher @ vue.common.js?e881:1644
Vue._mount @ vue.common.js?e881:2188
Vue$3.$mount @ vue.common.js?e881:5978
Vue$3.$mount @ vue.common.js?e881:8305
init @ vue.common.js?e881:2500
(anonymous) @ vue.common.js?e881:2654
createComponent @ vue.common.js?e881:4052
createElm @ vue.common.js?e881:3995
createChildren @ vue.common.js?e881:4103
createElm @ vue.common.js?e881:4028
patch @ vue.common.js?e881:4446
Vue._update @ vue.common.js?e881:2215
(anonymous) @ vue.common.js?e881:2189
get @ vue.common.js?e881:1652
Watcher @ vue.common.js?e881:1644
Vue._mount @ vue.common.js?e881:2188
Vue$3.$mount @ vue.common.js?e881:5978
Vue$3.$mount @ vue.common.js?e881:8305
init @ vue.common.js?e881:2500
createComponent @ vue.common.js?e881:4052
createElm @ vue.common.js?e881:3995
patch @ vue.common.js?e881:4483
Vue._update @ vue.common.js?e881:2215
(anonymous) @ vue.common.js?e881:2189
get @ vue.common.js?e881:1652
Watcher @ vue.common.js?e881:1644
Vue._mount @ vue.common.js?e881:2188
Vue$3.$mount @ vue.common.js?e881:5978
Vue$3.$mount @ vue.common.js?e881:8305
initRender @ vue.common.js?e881:2916
Vue._init @ vue.common.js?e881:3296
Vue$3 @ vue.common.js?e881:3343
(anonymous) @ main.js?3479:13
(anonymous) @ app.js:2424
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ app.js:587
__webpack_require__ @ app.js:556
(anonymous) @ app.js:579
(anonymous) @ app.js:582
vue.common.js?e881:2961 Uncaught TypeError: Cannot read property 'hsv' of undefined
......
我也遇到这个问题，用法不对？
    

    <color-picker v-model="colors"></color-picker>

export default {
  data() {
    return {
      colors: {
        hex: "#194d33",
        hsl: {
          h: 150,
          s: 0.5,
          l: 0.2,
          a: 1
        },
        hsv: {
          h: 150,
          s: 0.66,
          v: 0.3,
          a: 1
        },
        rgba: {
          r: 25,
          g: 77,
          b: 51,
          a: 1
        },
        a: 1
      }.....

请问哪里不对么？

**Comment by linx4200** [comment]
@zzzzzyb 请提供 vue 版本号，也麻烦编辑一下代码片段的格式，以便我们更好的追踪问题。谢谢。

**Comment by zzzzzyb** [comment]
@linx4200  "vue": "^2.1.0" ，vue-cli创建的项目

**Comment by linx4200** [comment]
@zzzzzyb 

根据你现在提供的代码片段，无法重现问题。

另外，在报错信息中，发现了 `Error when rendering component at src/components/common/Saturation.vue`.  暂时 `common` 下的组件目前不能被独立引用使用。

暂时关闭 issue, 如果还有这个问题，请提供可运行的 demo 代码，reopen issue，谢谢。
