### ISSUE TITLE
Add alpha on/off option please

### ISSUE THREAD

**Issue by Riant** [xiaokaike/vue-color#88]
Most times we do not need the alpha setting, if we can set it as disabled or hide the alpha slider bar, that's better, thanks

**Comment by linx4200** [comment]
Added this feature in 2.4.1. Please upgrade to this latest version. And thanks for your feedback.

Here is the example:

```
<chrome-picker :value="colors" :disableAlpha="true"></chrome-picker>
<sketch-picker v-model="colors" :disableAlpha="true"></sketch-picker>
```

**Comment by sarkiroka** [comment]
I think it would be a good idea to write this into the readme file :)
