### ISSUE TITLE
自動切換色彩格式

### ISSUE THREAD

**Issue by brownsugar** [xiaokaike/vue-color#89]
建議滑動透明度橫桿時，下方 HEX 自動切換成 rgba 模式（如 Chrome developer tools 的挑色器）
![image](https://user-images.githubusercontent.com/2935980/30511014-90b0ea02-9b02-11e7-9318-d829d5c320b9.png)

**Comment by linx4200** [comment]
好的，加入 todo list 了。

**Comment by linx4200** [comment]
2.4.1 版本加入了此功能，欢迎升级。
