### ISSUE TITLE
Adjust presets on Sketch-colorpicker

### ISSUE THREAD

**Issue by FranzSkuffka** [xiaokaike/vue-color#9]
It seems that I can not feed any custom swatches to the sketch colorpicker. that would be super useful :)

**Comment by linx4200** [comment]
The swaches can be customize now! Please upgrade to the latest version. And the usage is down blow:

```html
/* presetColors accepts an array of colors */
<sketch v-model="colors" :presetColors="presetColors"></sketch>
```
