### ISSUE TITLE
swatches组件下colorMap数组中添加黑色报错

### ISSUE THREAD

**Issue by Mugeda** [xiaokaike/vue-color#91]
报错信息如下  Cannot read property '900' of undefined
var colorMap = [
  'red', 'black'
],在其后面追加了黑色后就出现报错，多指教

**Comment by xiaokaike** [comment]
@Mugeda 能附上具体的代码么，是用在什么组件？

**Comment by linx4200** [comment]
`Swatches` 组件内使用 [Google Material Design 内的颜色设定](https://material.io/guidelines/style/color.html#color-color-palette),  的确现在添加 `Black` 和 `White` 报错，因为 `Black` 和 `White` 没有渐变选择，计划 2.4.2 版本会修复这个 bug, 如果需要添加 `#ffffff` 和 `#000000`，建议暂时使用 `palette` 属性传入你自己的调色板：

```html
<swatches-picker v-model="colors" :palette="['#fff', '#000']"></swatches-picker>
```
