### ISSUE TITLE
Server-side rendered

### ISSUE THREAD

**Issue by elliotlings** [xiaokaike/vue-color#92]
Do you know whether this is supposed to work server-side, I get the following error but not sure if I'm doing something wrong.

```
window is not defined
```

I've tried loading it asynchronously but without success

```
components: {
    ColorPicker: () => System.import('vue-color').Sketch,
},
```

**Comment by elliotlings** [comment]
This is the temporary solution I have at the moment.

```
components: {
    ColorPicker(resolve, reject) {
        if (typeof window == 'undefined') {
            return reject();
        }

        System.import('vue-color').then(module => resolve(module.Sketch));
    },
},
```

**Comment by linx4200** [comment]
We are sorry that vue-color is not compatible with server-side rendering currently, but we already plan to add this feature soon.  Please stay tuned. Thanks.

**Comment by elliotlings** [comment]
No problem, thanks for the update :)
