### ISSUE TITLE
[Feature] Disable/hide numeric fields

### ISSUE THREAD

**Issue by derekphilipau** [xiaokaike/vue-color#94]
Just as you have the "disableAlpha" property to remove alpha, I think it would be good to have a "disableFields" property to remove the fields, e.g.  `<div class="vc-chrome-fields-wrap" v-if="!disableFields">`

For many users, they are not geeks and don't care about numeric values of the color!

Great work, very useful, thanks!

**Comment by linx4200** [comment]
@derekphilipau  Thanks for your feedback. I think it's resonable, and we will put it into our todo list and implement it maybe in the next version.

Of cource, contribution is welcome!  😄😄😄

**Comment by derekphilipau** [comment]
My use case is probably too specific, I just want simplest RGB value possible.  Just in case someone is interested I [modified the Chrome component](https://github.com/derekphilipau/vue-color) to: a) not show an "active-color" swatch, b) not show alpha, c) button on parent controls show/hide of color component, d) button background/text color dependent upon color value.  vue-color is really nice and easy to customize, thanks!
<img width="799" alt="screen shot 2017-11-17 at 10 04 06" src="https://user-images.githubusercontent.com/22045002/32925854-c7a45f9e-cb09-11e7-97c0-0eb82c398c75.png">

**Comment by linx4200** [comment]
@derekphilipau   In your case, I think using `Saturation` and `Hue` direactly to compose your component would be a better option. 

And we released 2.4.3 just now. In this new release we added `disableFields` props to help hide the numberic fields.  Check [this pr](https://github.com/xiaokaike/vue-color/pull/98/files) for more info.

Thanks for your feedback!
