### ISSUE TITLE
Misalignment between cursor inside color-picker and mouse pointer

### ISSUE THREAD

**Issue by NNTin** [xiaokaike/vue-color#97]
`div#parent{
zoom: 1.4;
-moz-transform: scale(1.4);
}`

When CSS-zooming the cursor inside the color-picker is misaligned with the mouse pointer. 
[Video demonstration](https://my.mixtape.moe/dgjgaf.mp4)

**Comment by linx4200** [comment]
Sorry.  I think this is a  rare situation and there is no easy work around. Close this issue for now. Maybe will fix it someday.
